### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/emulsion#58]
To make Emulsion at least as useful as chat-linker and actually better (the reason for the existence of this project), we need to solve all of the following tasks:

- [x] #16: Serilog logger
- [x] #17: Make sure the client properly reconnects to both Telegram and XMPP after network outage
- [x] #18: XMPP room connection handler
- [x] #29: Decouple message queues from actors
- [x] #37: Clear the message factory architecture
- [x] #40: Add a Dockerfile
- [x] #41: Doesn't properly reconnect after proper server disconnection
- [x] #42: Doesn't properly reconnect after network outage
- [x] #44: Properly handle Telegram replies
- [x] #47: Translate forward messages from Telegram with their authors
- [x] #49: Support links from Telegram
- [x] #53: O01eg incident
- [x] #54: Bot mirrors Telegram message into Telegram
- [x] #55: Stop trying to send the messages while sleeping or connecting
- [x] #56: Reliable XMPP room connection
- [x] #57: Ignore private XMPP messages
- [x] #72: Forwarded message should be fully covered by quote prefix
- [x] #75: Formatting of Telegram replies to bot messages
- [x] #82: Queued messages aren't processed sometimes

After these're solved, I think that the bot is of production quality and we may start using it for codingteam chat linking.

**Comment by ForNeVeR** [comment]
Release 1.0.0 is created. Case closed.
